"""
Q1 word data — January (31) + February (28) + March (31) = 90 words
Each entry maps directly to make_page() kwargs.
"""

WORDS = [

    # ═══════════════════════════════════════════════════════════════════════════
    # JANUARY — The World's Most Celebrated Untranslatable Words
    # ═══════════════════════════════════════════════════════════════════════════

    dict(day=1, date="January 1", word="Hygge", language="Danish", country="Denmark", capital="Copenhagen",
         pronunciation="[ HUE-gah ]",
         definition="The art of creating warm, cozy moments of togetherness that nurture a deep sense of well-being and contentment.",
         etymology="From Old Norse hygga — to comfort, to console. Related to the English word hug.",
         example="She lit candles, brewed tea, and let hygge fill the quiet Sunday afternoon.",
         cultural_note="Danes consistently rank among the world's happiest people — and hygge is widely cited as their secret.",
         related="Gezellig (Dutch)  ·  Gemütlich (German)  ·  Mysig (Swedish)",
         quote="Life itself is the most wonderful fairy tale.",
         quote_author="Hans Christian Andersen", out_name="word_jan01.png"),

    dict(day=2, date="January 2", word="Saudade", language="Portuguese", country="Portugal", capital="Lisbon",
         pronunciation="[ saw-DAH-deh ]",
         definition="A deep, bittersweet longing for someone or something beloved that is absent, lost, or may never have truly existed.",
         etymology="From Latin solitatem — solitude. Shaped by centuries of Portuguese seafaring and exile.",
         example="Listening to old records alone, he was quietly overcome by saudade.",
         cultural_note="Saudade is the emotional soul of Portugal and Brazil — the very heart of fado music.",
         related="Hiraeth (Welsh)  ·  Toska (Russian)  ·  Sehnsucht (German)",
         quote="Everything is worth it if the soul is not small.",
         quote_author="Fernando Pessoa", out_name="word_jan02.png"),

    dict(day=3, date="January 3", word="Hiraeth", language="Welsh", country="Wales", capital="Cardiff",
         pronunciation="[ HEER-eyeth ]",
         definition="A longing for home — or for a past that may never have existed — tinged with grief, nostalgia, and an ache for belonging.",
         etymology="From hir (long) + aeth (gone, grief). Ancient Welsh; considered untranslatable even within Celtic languages.",
         example="Walking through the old village, she felt hiraeth for a childhood she could no longer quite remember.",
         cultural_note="Hiraeth is considered the defining emotion of the Welsh soul — inseparable from its mist-covered hills and long history.",
         related="Saudade (Portuguese)  ·  Sehnsucht (German)  ·  Toska (Russian)",
         quote="To live in Wales is to be conscious at dusk of the spilled blood of heroes.",
         quote_author="Dylan Thomas", out_name="word_jan03.png"),

    dict(day=4, date="January 4", word="Waldeinsamkeit", language="German", country="Germany", capital="Berlin",
         pronunciation="[ VALD-eye-n-zam-kite ]",
         definition="The serene, almost mystical solitude felt deep in a forest, where the self dissolves into the natural world.",
         etymology="From Wald (forest) + Einsamkeit (solitude). Coined by Romantic poet Ludwig Tieck in 1802.",
         example="He turned off his phone and walked until waldeinsamkeit washed over him completely.",
         cultural_note="Central to German Romanticism, the forest has always been a sacred, almost mythological space in the Germanic imagination.",
         related="Friluftsliv (Norwegian)  ·  Querencia (Spanish)  ·  Komorebi (Japanese)",
         quote="In every walk with nature, one receives far more than he seeks.",
         quote_author="Johann Wolfgang von Goethe", out_name="word_jan04.png"),

    dict(day=5, date="January 5", word="Sehnsucht", language="German", country="Germany", capital="Berlin",
         pronunciation="[ ZAYN-zookt ]",
         definition="An intense, inconsolable yearning for something indefinable — an ache for beauty, meaning, or a life not yet lived.",
         etymology="From sehnen (to yearn) + Sucht (craving, addiction). Used by Goethe to capture the soul of Romanticism.",
         example="Every sunset filled her with sehnsucht — a beautiful sorrow she could never quite name.",
         cultural_note="C.S. Lewis called sehnsucht 'the inconsolable longing' and saw it as humanity's deepest spiritual instinct.",
         related="Saudade (Portuguese)  ·  Hiraeth (Welsh)  ·  Toska (Russian)",
         quote="Longing is the agony of the nearness of the distant.",
         quote_author="Friedrich Hölderlin", out_name="word_jan05.png"),

    dict(day=6, date="January 6", word="Toska", language="Russian", country="Russia", capital="Moscow",
         pronunciation="[ TAHS-kah ]",
         definition="A profound spiritual anguish with no identifiable cause — a dull ache of the soul that ranges from mild melancholy to mortal dread.",
         etymology="Old Russian; related to toskovát — to feel deep longing. Vladimir Nabokov declared it utterly untranslatable.",
         example="On grey winter afternoons, a heavy toska settled over the city like fog.",
         cultural_note="Nabokov wrote that toska at its deepest is 'a longing with nothing to long for' — a uniquely Russian ache.",
         related="Sehnsucht (German)  ·  Saudade (Portuguese)  ·  Weltschmerz (German)",
         quote="What torture, to be always longing for that which is not.",
         quote_author="Fyodor Dostoevsky", out_name="word_jan06.png"),

    dict(day=7, date="January 7", word="Wabi-sabi", language="Japanese", country="Japan", capital="Tokyo",
         pronunciation="[ WAH-bee SAH-bee ]",
         definition="The beauty found in imperfection, impermanence, and incompleteness — an aesthetic philosophy that celebrates the transient and the rustic.",
         etymology="Wabi once meant loneliness in poverty; sabi, the beauty of aging and weathering. Together, a philosophy of humble beauty.",
         example="The cracked teacup repaired with gold embodied wabi-sabi — more beautiful for having been broken.",
         cultural_note="Rooted in Zen Buddhism, wabi-sabi is the antidote to perfection — a reminder that all things pass, and that is enough.",
         related="Kintsugi (Japanese)  ·  Mono no aware (Japanese)  ·  Sabi (Japanese)",
         quote="Every day is a journey, and the journey itself is home.",
         quote_author="Matsuo Bashō", out_name="word_jan07.png"),

    dict(day=8, date="January 8", word="Fernweh", language="German", country="Germany", capital="Berlin",
         pronunciation="[ FERN-vay ]",
         definition="A deep, painful longing for far-off places — the ache of the wandering spirit that has not yet left.",
         etymology="From fern (distant) + Weh (pain, ache). The melancholic twin of Wanderlust — the wound of not yet having gone.",
         example="The travel photos only deepened his fernweh — every image a window onto a life not yet lived.",
         cultural_note="While Wanderlust is the desire to travel, Fernweh is the pain of staying still — a distinctly German shade of longing.",
         related="Wanderlust (German)  ·  Resfeber (Swedish)  ·  Hiraeth (Welsh)",
         quote="Not until we are lost do we begin to find ourselves.",
         quote_author="Henry David Thoreau", out_name="word_jan08.png"),

    dict(day=9, date="January 9", word="Mamihlapinatapai", language="Yaghan", country="Chile", capital="Santiago",
         pronunciation="[ mah-mee-lah-pee-nah-TAH-pie ]",
         definition="A look shared between two people, each wishing the other would initiate something they both desire but neither dares begin.",
         etymology="From the Yaghan language of Tierra del Fuego. Once listed in the Guinness Book as the world's most succinct word.",
         example="Across the dinner table, they shared a long mamihlapinatapai before she finally spoke.",
         cultural_note="The Yaghan people of southern Chile developed one of the world's most expressive languages — much of it now lost.",
         related="Iktsuarpok (Inuit)  ·  Koi no yokan (Japanese)  ·  Forelsket (Norwegian)",
         quote="The bravest thing you can do is to begin.",
         quote_author="Gabriela Mistral", out_name="word_jan09.png"),

    dict(day=10, date="January 10", word="Litost", language="Czech", country="Czech Republic", capital="Prague",
         pronunciation="[ LEE-tosht ]",
         definition="A state of agonizing torment caused by the sudden sight of one's own misery — often followed by an urge to retaliate.",
         etymology="Czech, from lítost — pity or sorrow. Milan Kundera elevated it to a philosophical concept in The Book of Laughter and Forgetting.",
         example="He felt litost when his friend, so effortlessly graceful, swam past him in the open water.",
         cultural_note="Milan Kundera called litost 'a state of torment created by the sudden sight of one's own misery' — uniquely Central European.",
         related="Toska (Russian)  ·  Weltschmerz (German)  ·  Acedia (Latin)",
         quote="The struggle of man against power is the struggle of memory against forgetting.",
         quote_author="Milan Kundera", out_name="word_jan10.png"),

    dict(day=11, date="January 11", word="Koselig", language="Norwegian", country="Norway", capital="Oslo",
         pronunciation="[ KOO-se-lee ]",
         definition="A warm, intimate sense of coziness — the feeling of being comfortably enclosed with people or nature you love.",
         etymology="From Norwegian kose seg — to enjoy oneself. Related to the German gemütlich and Danish hygge.",
         example="The cabin was small, the candles were low, and the snow was falling — perfectly koselig.",
         cultural_note="In Norway, koselig extends beyond indoors — a winter hike with friends, hot drinks included, is deeply koselig too.",
         related="Hygge (Danish)  ·  Gezellig (Dutch)  ·  Gemütlichkeit (German)",
         quote="There is nothing like staying at home for real comfort.",
         quote_author="Henrik Ibsen", out_name="word_jan11.png"),

    dict(day=12, date="January 12", word="Gezellig", language="Dutch", country="Netherlands", capital="Amsterdam",
         pronunciation="[ heh-ZEL-ikh ]",
         definition="A convivial, cozy togetherness — the warm atmosphere created when good people share good company in a comfortable space.",
         etymology="From gezel (companion, fellow). Related to the German Geselle (journeyman, companion). Untranslatable even to neighbouring languages.",
         example="The old café was gezellig — low lights, conversation, and rain on the cobblestones outside.",
         cultural_note="Gezelligheid is considered the highest social virtue in Dutch culture — the measure of a truly good evening.",
         related="Hygge (Danish)  ·  Koselig (Norwegian)  ·  Gemütlichkeit (German)",
         quote="The pleasure of a single touch of happiness is worth a whole lifetime of trouble.",
         quote_author="Baruch Spinoza", out_name="word_jan12.png"),

    dict(day=13, date="January 13", word="Gemütlichkeit", language="German", country="Germany", capital="Berlin",
         pronunciation="[ geh-MYOOT-likh-kite ]",
         definition="A feeling of warmth, friendliness, and belonging — the comfortable, unhurried ease of a space that makes you feel at home.",
         etymology="From Gemüt (soul, heart, mind) — a word that itself resists translation. Gemütlichkeit is the atmosphere that emerges from it.",
         example="The old brewery, with its long wooden tables and amber light, was all Gemütlichkeit.",
         cultural_note="Gemütlichkeit is inseparable from German social culture — the Biergarten, the Christmas market, the long Sunday lunch.",
         related="Hygge (Danish)  ·  Gezellig (Dutch)  ·  Koselig (Norwegian)",
         quote="Nothing great in the world was accomplished without passion.",
         quote_author="Georg Wilhelm Friedrich Hegel", out_name="word_jan13.png"),

    dict(day=14, date="January 14", word="Ikigai", language="Japanese", country="Japan", capital="Tokyo",
         pronunciation="[ ee-kee-GUY ]",
         definition="One's reason for being — the intersection of what you love, what you are good at, what the world needs, and what you can be paid for.",
         etymology="From iki (life, to live) + gai (worth, value). The concept emerged from Okinawan philosophy of purpose and longevity.",
         example="She found her ikigai the day she realised her love of teaching could also sustain her.",
         cultural_note="Okinawa, where ikigai is a way of life, has one of the world's highest concentrations of centenarians.",
         related="Raison d'être (French)  ·  Eudaimonia (Greek)  ·  Ubuntu (Zulu)",
         quote="He who has a why to live can bear almost any how.",
         quote_author="Friedrich Nietzsche", out_name="word_jan14.png"),

    dict(day=15, date="January 15", word="Ubuntu", language="Zulu", country="South Africa", capital="Pretoria",
         pronunciation="[ oo-BOON-too ]",
         definition="A philosophy of shared humanity — the belief that a person is a person only through other people, that we exist in relationship.",
         etymology="From the Nguni proverb umuntu ngumuntu ngabantu: 'A person is a person through other persons.'",
         example="The village ran on ubuntu — no one celebrated alone, and no one grieved alone.",
         cultural_note="Nelson Mandela embodied ubuntu throughout his life. Archbishop Tutu called it the essence of African philosophy.",
         related="Ikigai (Japanese)  ·  Philotimo (Greek)  ·  Meraki (Greek)",
         quote="It always seems impossible until it's done.",
         quote_author="Nelson Mandela", out_name="word_jan15.png"),

    dict(day=16, date="January 16", word="Meraki", language="Greek", country="Greece", capital="Athens",
         pronunciation="[ meh-RAH-kee ]",
         definition="Doing something with soul, creativity, and love — leaving a piece of yourself in everything you make or do.",
         etymology="From the Turkish merak (curiosity, passion). Adopted into Greek to describe an untranslatable quality of devotion.",
         example="You could taste the meraki in every dish she made — love was the secret ingredient.",
         cultural_note="Meraki is said to be visible in Greek food, music, and craftsmanship — a culture that pours itself into everything.",
         related="Ikigai (Japanese)  ·  Kodawari (Japanese)  ·  Joie de vivre (French)",
         quote="The secret of happiness is freedom, and the secret of freedom is courage.",
         quote_author="Thucydides", out_name="word_jan16.png"),

    dict(day=17, date="January 17", word="Sisu", language="Finnish", country="Finland", capital="Helsinki",
         pronunciation="[ SEE-soo ]",
         definition="An extraordinary inner strength and stoic determination in the face of adversity — the grit to persist long after willpower is exhausted.",
         etymology="Ancient Finnish, with no clear etymology. First used in a 1745 Finnish dictionary to describe a quality of the Finnish character.",
         example="It was sisu that kept her going through the third winter without heating.",
         cultural_note="Sisu is considered the national soul of Finland — what carried a small nation through its wars and long dark winters.",
         related="Chutzpah (Yiddish)  ·  Perseverance (English)  ·  Ubuntu (Zulu)",
         quote="I care not what others think of what I do, but I care very much about what I think of what I do.",
         quote_author="Jean Sibelius", out_name="word_jan17.png"),

    dict(day=18, date="January 18", word="Lagom", language="Swedish", country="Sweden", capital="Stockholm",
         pronunciation="[ LAH-gom ]",
         definition="Not too much, not too little — just the right amount. A philosophy of balance, moderation, and appropriateness.",
         etymology="Possibly from laget om — 'around the team', from the Viking tradition of passing a drinking horn that everyone must share fairly.",
         example="The apartment was lagom — enough space, enough light, enough quiet.",
         cultural_note="Lagom is the organizing principle of Swedish society: fairness, equality, and the wisdom of the middle path.",
         related="Hygge (Danish)  ·  Wabi-sabi (Japanese)  ·  Sophrosyne (Greek)",
         quote="A crust eaten in peace is better than a banquet partaken in anxiety.",
         quote_author="Astrid Lindgren", out_name="word_jan18.png"),

    dict(day=19, date="January 19", word="Friluftsliv", language="Norwegian", country="Norway", capital="Oslo",
         pronunciation="[ FREE-loofts-leev ]",
         definition="A philosophy of outdoor life — the belief that time spent in nature is essential to the human soul, in any season and any weather.",
         etymology="From fri (free) + luft (air) + liv (life). Coined by playwright Henrik Ibsen in 1859 in his poem On the Heights.",
         example="Rain or shine, the children were sent outside — friluftsliv was not a hobby but a way of life.",
         cultural_note="Norwegians live by the saying 'there is no bad weather, only bad clothing.' Friluftsliv is a national birthright.",
         related="Waldeinsamkeit (German)  ·  Hygge (Danish)  ·  Shinrin-yoku (Japanese)",
         quote="The strongest man in the world is he who stands most alone.",
         quote_author="Henrik Ibsen", out_name="word_jan19.png"),

    dict(day=20, date="January 20", word="Lykke", language="Danish", country="Denmark", capital="Copenhagen",
         pronunciation="[ LIH-keh ]",
         definition="Happiness — but a Danish happiness rooted in balance, community, and the quiet satisfaction of a life well lived.",
         etymology="From Old Norse lukka — luck, fortune. In Danish, lykke encompasses both luck and a deeper, earned happiness.",
         example="She didn't chase lykke — she built it, carefully, out of small pleasures and good relationships.",
         cultural_note="Denmark's pursuit of lykke, built on social trust and equality, is why it consistently tops the world happiness rankings.",
         related="Hygge (Danish)  ·  Eudaimonia (Greek)  ·  Ikigai (Japanese)",
         quote="First, learn to be happy with little, and then, learn to be happy with more.",
         quote_author="Søren Kierkegaard", out_name="word_jan20.png"),

    dict(day=21, date="January 21", word="Forelsket", language="Norwegian", country="Norway", capital="Oslo",
         pronunciation="[ for-ELL-sket ]",
         definition="The overwhelming, euphoric rush of falling in love — that early, giddy feeling before the world settles back into focus.",
         etymology="From Norwegian forelske seg — to fall in love. Related to the German verliebt; describes the initial intoxicating phase.",
         example="He barely slept that week — forelsket had seized his mind completely.",
         cultural_note="Norwegian literature is rich with forelsket — a culture that takes both nature and love with great seriousness.",
         related="Koi no yokan (Japanese)  ·  Retrouvailles (French)  ·  Ya'aburnee (Arabic)",
         quote="To love and to be loved is to feel the sun from both sides.",
         quote_author="Knut Hamsun", out_name="word_jan21.png"),

    dict(day=22, date="January 22", word="Querencia", language="Spanish", country="Spain", capital="Madrid",
         pronunciation="[ keh-REN-see-ah ]",
         definition="A place from which one's strength is drawn — a refuge, real or imagined, where one feels safe and fully oneself.",
         etymology="From the Spanish querer (to desire, to love). Used in bullfighting to describe the spot in the ring the bull returns to.",
         example="The old library was her querencia — the only place where her thoughts felt entirely her own.",
         cultural_note="Originally a bullfighting term, querencia has become a broader philosophy of the spaces that restore us.",
         related="Heimat (German)  ·  Hiraeth (Welsh)  ·  Natsukashii (Japanese)",
         quote="One cannot think well, love well, sleep well, if one has not dined well.",
         quote_author="Miguel de Cervantes", out_name="word_jan22.png"),

    dict(day=23, date="January 23", word="Sobremesa", language="Spanish", country="Spain", capital="Madrid",
         pronunciation="[ so-breh-MEH-sah ]",
         definition="The time spent lingering at the table after a meal is finished — conversation, wine, and the reluctance to let the moment end.",
         etymology="From sobre (over, upon) + mesa (table). Literally 'over the table' — the sacred after-meal ritual of Spanish culture.",
         example="They finished eating at two, but sobremesa carried them all the way to five.",
         cultural_note="In Spain, sobremesa can last longer than the meal itself — a practice that baffles Northern Europeans and enchants everyone else.",
         related="Dolce far niente (Italian)  ·  Fika (Swedish)  ·  Hygge (Danish)",
         quote="To eat is a necessity, but to eat intelligently is an art.",
         quote_author="Francisco de Quevedo", out_name="word_jan23.png"),

    dict(day=24, date="January 24", word="Dolce far niente", language="Italian", country="Italy", capital="Rome",
         pronunciation="[ DOHL-cheh far nee-EN-teh ]",
         definition="The sweetness of doing nothing — the pleasure of pure idleness, savoured without guilt or the pressure to be productive.",
         etymology="Literally 'sweet doing nothing' in Italian. The phrase appears in 17th-century literature but captures a timeless Italian attitude.",
         example="They spent the afternoon in dolce far niente — sun-warmed, unhurried, perfectly content.",
         cultural_note="While Anglo-Saxon culture sees idleness as waste, Italians have long understood it as one of life's genuine pleasures.",
         related="Sobremesa (Spanish)  ·  Lagom (Swedish)  ·  Fika (Swedish)",
         quote="The art of life lies in a constant readjustment to our surroundings.",
         quote_author="Italo Calvino", out_name="word_jan24.png"),

    dict(day=25, date="January 25", word="Joie de vivre", language="French", country="France", capital="Paris",
         pronunciation="[ zhwah deh VEE-vreh ]",
         definition="An exuberant, all-encompassing delight in being alive — not mere happiness, but a radiant, effervescent love of life itself.",
         etymology="Literally 'joy of living' in French. Popularised in 19th-century literature; Zola used it as a novel title in 1884.",
         example="She entered the party and the room changed — her joie de vivre was simply contagious.",
         cultural_note="More than a feeling, joie de vivre is a French way of being — present, sensuous, and unafraid of pleasure.",
         related="Kefi (Greek)  ·  Meraki (Greek)  ·  Lykke (Danish)",
         quote="The secret of happiness is variety, but the secret of variety, like the secret of all spices, is knowing when to use it.",
         quote_author="Albert Camus", out_name="word_jan25.png"),

    dict(day=26, date="January 26", word="L'esprit de l'escalier", language="French", country="France", capital="Paris",
         pronunciation="[ les-PREE deh les-kal-YAY ]",
         definition="The perfect, devastating comeback you think of only after leaving — the wit that arrives too late, on the staircase on the way out.",
         etymology="Literally 'staircase wit'. Coined by French philosopher Denis Diderot in 1773 — he thought of the perfect reply while descending the stairs.",
         example="He lay awake at midnight, tormented by l'esprit de l'escalier — three perfect words, six hours too late.",
         cultural_note="Diderot's staircase has haunted every dinner party since — the universal ache of the comeback that never was.",
         related="Treppenwitz (German)  ·  Backpfeifengesicht (German)  ·  Forelsket (Norwegian)",
         quote="The secret of getting ahead is getting started.",
         quote_author="Marcel Proust", out_name="word_jan26.png"),

    dict(day=27, date="January 27", word="Dépaysement", language="French", country="France", capital="Paris",
         pronunciation="[ day-pay-EEZ-mahn ]",
         definition="The disorienting, vertiginous feeling of being in a foreign place — the sense of self that dissolves when context disappears.",
         etymology="From dépayser — to remove someone from their country. From pays (country, homeland). The feeling of being unmoored from the familiar.",
         example="The first morning in Tokyo, the dépaysement was total — beautiful and slightly frightening.",
         cultural_note="French writers have long treated dépaysement not as a hardship but as a gift — the creative shock of the unfamiliar.",
         related="Fernweh (German)  ·  Hiraeth (Welsh)  ·  Sehnsucht (German)",
         quote="The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.",
         quote_author="Marcel Proust", out_name="word_jan27.png"),

    dict(day=28, date="January 28", word="Flâneur", language="French", country="France", capital="Paris",
         pronunciation="[ flah-NER ]",
         definition="One who wanders the city without destination — an urban stroller who observes the spectacle of street life with detached, artistic curiosity.",
         etymology="From flâner — to stroll, to lounge. Theorised by poet Charles Baudelaire as a mode of artistic existence in the modern city.",
         example="He had no errands, no route, no hurry — he was simply a flâneur, possessed by Paris.",
         cultural_note="Walter Benjamin called the flâneur the detective of the city — reading the streets like a text, seeing what others walk past.",
         related="Waldeinsamkeit (German)  ·  Friluftsliv (Norwegian)  ·  Meraki (Greek)",
         quote="For the perfect flâneur, it is an immense joy to set up house in the heart of the multitude.",
         quote_author="Charles Baudelaire", out_name="word_jan28.png"),

    dict(day=29, date="January 29", word="Raison d'être", language="French", country="France", capital="Paris",
         pronunciation="[ ray-ZON DET-reh ]",
         definition="The fundamental purpose that justifies one's existence — the reason a person, institution, or thing must exist.",
         etymology="Literally 'reason for being'. Adopted into English in the 19th century. Related to existentialist philosophy of meaning and purpose.",
         example="After the children left home, she had to rediscover her raison d'être — it turned out to be painting.",
         cultural_note="French existentialism — Sartre, Camus — made the question of raison d'être the central problem of modern life.",
         related="Ikigai (Japanese)  ·  Eudaimonia (Greek)  ·  Ubuntu (Zulu)",
         quote="Man is condemned to be free; because once thrown into the world, he is responsible for everything he does.",
         quote_author="Jean-Paul Sartre", out_name="word_jan29.png"),

    dict(day=30, date="January 30", word="Eudaimonia", language="Greek", country="Greece", capital="Athens",
         pronunciation="[ yoo-dye-MOH-nee-ah ]",
         definition="The flourishing of full human potential — not fleeting happiness, but the deep contentment of a life lived with virtue and purpose.",
         etymology="From eu (well) + daimon (spirit, inner self). Aristotle's highest good: not pleasure, but the full expression of what a human being can be.",
         example="She didn't pursue happiness — she pursued eudaimonia, and happiness came along for the ride.",
         cultural_note="For Aristotle, eudaimonia was the purpose of human life — accessible only through virtue, friendship, and meaningful work.",
         related="Ikigai (Japanese)  ·  Sisu (Finnish)  ·  Lykke (Danish)",
         quote="Happiness depends upon ourselves.",
         quote_author="Aristotle", out_name="word_jan30.png"),

    dict(day=31, date="January 31", word="Wanderlust", language="German", country="Germany", capital="Berlin",
         pronunciation="[ VAHN-der-loost ]",
         definition="A deep, irresistible desire to travel and explore the world — not restlessness, but an authentic hunger for new places and experiences.",
         etymology="From wandern (to hike, to travel) + Lust (desire, pleasure). Entered English in the early 20th century from German Romantic literature.",
         example="She quit the job on Tuesday. By Thursday, wanderlust had already chosen her next destination.",
         cultural_note="The German Romantic tradition elevated travel to a spiritual act — wanderlust is its permanent, irresistible legacy.",
         related="Fernweh (German)  ·  Resfeber (Swedish)  ·  Dépaysement (French)",
         quote="All truly great thoughts are conceived by walking.",
         quote_author="Friedrich Nietzsche", out_name="word_jan31.png"),

    # ═══════════════════════════════════════════════════════════════════════════
    # FEBRUARY — Love, Longing & Connection
    # ═══════════════════════════════════════════════════════════════════════════

    dict(day=32, date="February 1", word="Ya'aburnee", language="Arabic", country="Lebanon", capital="Beirut",
         pronunciation="[ yah-ah-BOOR-nee ]",
         definition="A declaration of love so total it means 'may you bury me' — I love you so deeply I could not survive you.",
         etymology="From the Arabic root meaning 'to bury'. A hyperbolic expression of love common across the Arab world.",
         example="She whispered ya'aburnee to her sleeping child — may I go first, because I cannot imagine the world without you.",
         cultural_note="In Arab cultures, love is expressed through vivid, almost violent poetry. Ya'aburnee is its most tender extremity.",
         related="Cafuné (Portuguese)  ·  Forelsket (Norwegian)  ·  Koi no yokan (Japanese)",
         quote="Love is not love which alters when it alteration finds.",
         quote_author="Kahlil Gibran", out_name="word_feb01.png"),

    dict(day=33, date="February 2", word="Cafuné", language="Brazilian Portuguese", country="Brazil", capital="Brasília",
         pronunciation="[ kah-foo-NEH ]",
         definition="The tender, loving act of running one's fingers through a loved one's hair — an intimate gesture of affection without words.",
         etymology="Of uncertain origin — possibly from African Bantu languages brought to Brazil during the colonial period.",
         example="She sat on the floor reading while he did cafuné — neither speaking, both entirely content.",
         cultural_note="Brazil's language is rich with words for physical tenderness — a culture that understands touch as its own grammar of love.",
         related="Amae (Japanese)  ·  Ya'aburnee (Arabic)  ·  Forelsket (Norwegian)",
         quote="Tenderness is the repose of passion.",
         quote_author="José Saramago", out_name="word_feb02.png"),

    dict(day=34, date="February 3", word="Retrouvailles", language="French", country="France", capital="Paris",
         pronunciation="[ reh-troo-VY ]",
         definition="The joy of reuniting with someone after a long separation — the happiness of rediscovering a person you have missed.",
         etymology="From retrouver — to find again, to rediscover. The prefix re- intensifies the joy of what was lost and is now returned.",
         example="After three years apart, the retrouvailles was overwhelming — they simply held each other and laughed.",
         cultural_note="French culture has always understood that love deepens through absence — retrouvailles is the proof.",
         related="Iktsuarpok (Inuit)  ·  Forelsket (Norwegian)  ·  Saudade (Portuguese)",
         quote="The pleasure of reunion is worth the pain of separation.",
         quote_author="Victor Hugo", out_name="word_feb03.png"),

    dict(day=35, date="February 4", word="Koi no yokan", language="Japanese", country="Japan", capital="Tokyo",
         pronunciation="[ koy no yo-KAN ]",
         definition="The premonition, upon first meeting someone, that falling in love with them is inevitable — not love at first sight, but its foreboding.",
         etymology="From koi (romantic love) + yokan (premonition, feeling of what is to come). A subtle but certain knowing.",
         example="The first handshake lasted a moment too long — she felt koi no yokan before she knew his name.",
         cultural_note="Japanese culture is attuned to subtle emotional signals — koi no yokan is the art of reading what has not yet been said.",
         related="Forelsket (Norwegian)  ·  Mamihlapinatapai (Yaghan)  ·  Retrouvailles (French)",
         quote="To fall in love is to create a religion that has a fallible god.",
         quote_author="Haruki Murakami", out_name="word_feb04.png"),

    dict(day=36, date="February 5", word="Amae", language="Japanese", country="Japan", capital="Tokyo",
         pronunciation="[ ah-MAH-eh ]",
         definition="A pleasant, childlike dependence on another's love and goodwill — the comfort of knowing you are cared for without needing to ask.",
         etymology="From amaeru — to presume on another's affection, to act lovingly spoiled. Theorised by psychologist Takeo Doi as uniquely Japanese.",
         example="She didn't need to explain herself at home — amae made words unnecessary.",
         cultural_note="Psychologist Takeo Doi argued that amae is the key to understanding Japanese social behaviour and emotional life.",
         related="Cafuné (Portuguese)  ·  Ya'aburnee (Arabic)  ·  Naz (Urdu)",
         quote="The heart has its reasons which reason knows nothing of.",
         quote_author="Blaise Pascal", out_name="word_feb05.png"),

    dict(day=37, date="February 6", word="Iktsuarpok", language="Inuit", country="Canada", capital="Ottawa",
         pronunciation="[ ik-TSOO-ar-pok ]",
         definition="The restless, anticipatory feeling of going outside repeatedly to check whether an expected guest has arrived.",
         etymology="From the Inuit language of the Arctic. One of many Inuit words for states of anticipation and emotional waiting.",
         example="The party was still an hour away, but iktsuarpok had him at the window every ten minutes.",
         cultural_note="Inuit languages encode nuanced emotional and environmental states for which other languages have no words at all.",
         related="Retrouvailles (French)  ·  Koi no yokan (Japanese)  ·  Forelsket (Norwegian)",
         quote="To wait is to love.",
         quote_author="Elias Asen", out_name="word_feb06.png"),

    dict(day=38, date="February 7", word="Mono no aware", language="Japanese", country="Japan", capital="Tokyo",
         pronunciation="[ moh-no no ah-WAH-reh ]",
         definition="The bittersweet awareness of impermanence — the gentle sadness and appreciation for all things precisely because they will not last.",
         etymology="From mono (things) + no (possessive) + aware (pathos, poignancy). Central to Japanese aesthetics since the Heian period.",
         example="She watched the last cherry blossoms fall and felt mono no aware — beauty and grief, perfectly fused.",
         cultural_note="The cherry blossom (sakura) is Japan's national symbol precisely because it exemplifies mono no aware — perfect and brief.",
         related="Wabi-sabi (Japanese)  ·  Saudade (Portuguese)  ·  Hiraeth (Welsh)",
         quote="In the autumn wind, I see the flowers of summer that have gone.",
         quote_author="Matsuo Bashō", out_name="word_feb07.png"),

    dict(day=39, date="February 8", word="Yūgen", language="Japanese", country="Japan", capital="Tokyo",
         pronunciation="[ YOO-gen ]",
         definition="A profound, mysterious sense of the universe's beauty — the awareness of the cosmos that is too deep for words, felt but never fully grasped.",
         etymology="From the Chinese characters for dim, dark (幽) + deep, profound (玄). Used in Noh theatre to describe the highest aesthetic quality.",
         example="Standing alone at the cliff's edge in fog, she experienced something close to yūgen.",
         cultural_note="Yūgen is the peak of Japanese aesthetics — not the beauty you see, but the beauty you feel behind what you see.",
         related="Wabi-sabi (Japanese)  ·  Mono no aware (Japanese)  ·  Sehnsucht (German)",
         quote="To watch the sun sink behind a flower-clad hill. To stand in the darkness and listen to the cry of distant birds.",
         quote_author="Zeami Motokiyo", out_name="word_feb08.png"),

    dict(day=40, date="February 9", word="Merak", language="Turkish", country="Turkey", capital="Ankara",
         pronunciation="[ meh-RAHK ]",
         definition="A pleasurable, introspective curiosity — the joyful pursuit of knowledge for its own sake, driven by a deep love of learning.",
         etymology="From Arabic ma'raka — battle, conflict, later softened to mean engaged curiosity. Absorbed into Turkish as an emotional orientation.",
         example="He spent hours down that particular rabbit hole, carried by pure merak — not seeking anything, just following wonder.",
         cultural_note="Merak is often cited as the quality shared by great scientists, philosophers, and artists — curiosity as a spiritual practice.",
         related="Ikigai (Japanese)  ·  Meraki (Greek)  ·  Eudaimonia (Greek)",
         quote="The one who asks questions never loses his way.",
         quote_author="Nazım Hikmet", out_name="word_feb09.png"),

    dict(day=41, date="February 10", word="Philotimo", language="Greek", country="Greece", capital="Athens",
         pronunciation="[ fee-LOH-tee-mo ]",
         definition="A complex virtue encompassing love of honour, dignity, generosity, and the deep sense of duty to one's community and family.",
         etymology="From philos (loving) + timi (honour, worth). Considered by many Greeks to be the highest and most untranslatable of all virtues.",
         example="He drove three hours to help a stranger fix a broken axle — that was philotimo.",
         cultural_note="Greeks consider philotimo their defining national virtue. Prime Minister Karamanlis once called it 'the most ancient Greek word.'",
         related="Ubuntu (Zulu)  ·  Sisu (Finnish)  ·  Meraki (Greek)",
         quote="The measure of a man is what he does with power.",
         quote_author="Plato", out_name="word_feb10.png"),

    dict(day=42, date="February 11", word="Kefi", language="Greek", country="Greece", capital="Athens",
         pronunciation="[ KEH-fee ]",
         definition="A state of passionate joy and high spirits — the communal ecstasy of music, dance, and togetherness that lifts the soul.",
         etymology="Possibly from Turkish keyif (pleasure, delight). In Greek, kefi is less about individual joy and more about shared, irresistible exuberance.",
         example="By midnight the wedding had reached kefi — plates were broken, strangers were dancing, nobody wanted it to end.",
         cultural_note="Kefi cannot be manufactured or scheduled. It arrives unexpectedly, seizes a room, and carries everyone along.",
         related="Joie de vivre (French)  ·  Meraki (Greek)  ·  Lykke (Danish)",
         quote="Wonder is the beginning of wisdom.",
         quote_author="Socrates", out_name="word_feb11.png"),

    dict(day=43, date="February 12", word="Razliubit", language="Russian", country="Russia", capital="Moscow",
         pronunciation="[ raz-lyoo-BEET ]",
         definition="The act of falling out of love — the slow, painful process of ceasing to love someone you once loved deeply.",
         etymology="From the Russian prefix raz- (undoing) + lyubit (to love). To unlove: the reverse journey no other language names so precisely.",
         example="He didn't leave — he just razlyubil, quietly, over a long winter, without either of them quite noticing.",
         cultural_note="Russian has a remarkable vocabulary for love's gradations — razliubit names the specific grief of love's quiet departure.",
         related="Saudade (Portuguese)  ·  Hiraeth (Welsh)  ·  Toska (Russian)",
         quote="Love is like a fever which comes and goes quite independently of the will.",
         quote_author="Leo Tolstoy", out_name="word_feb12.png"),

    dict(day=44, date="February 13", word="Pena ajena", language="Spanish", country="Mexico", capital="Mexico City",
         pronunciation="[ PEH-na ah-HEH-na ]",
         definition="The vicarious embarrassment felt on behalf of someone who is not embarrassed themselves — shame absorbed from another person.",
         etymology="From pena (embarrassment, grief) + ajena (belonging to another). Common in Mexican and Latin American Spanish.",
         example="She watched her boss give that speech and felt pena ajena so intense she had to leave the room.",
         cultural_note="The German Fremdschämen captures the same feeling. It is universal, but only some cultures have found words for it.",
         related="Fremdschämen (German)  ·  Schadenfreude (German)  ·  Litost (Czech)",
         quote="The more you know yourself, the more you forgive yourself.",
         quote_author="Octavio Paz", out_name="word_feb13.png"),

    dict(day=45, date="February 14", word="Onsra", language="Boro", country="India", capital="New Delhi",
         pronunciation="[ ON-srah ]",
         definition="The bittersweet knowledge that a love will not last — loving someone while knowing, in your heart, it is already ending.",
         etymology="From the Boro language of Northeast India (Assam). One of the rarest and most precise words for love's impermanence.",
         example="She loved him through the whole last summer knowing it was onsra — beautiful, and already past.",
         cultural_note="The Boro people of Assam have developed a rich emotional vocabulary. Onsra is their most poignant contribution to the world.",
         related="Mono no aware (Japanese)  ·  Saudade (Portuguese)  ·  Razliubit (Russian)",
         quote="What we call the beginning is often the end, and to make an end is to make a beginning.",
         quote_author="Rabindranath Tagore", out_name="word_feb14.png"),

    dict(day=46, date="February 15", word="Firgun", language="Hebrew", country="Israel", capital="Jerusalem",
         pronunciation="[ feer-GOON ]",
         definition="The pure, unselfish joy in another's success — celebrating someone else's good fortune wholeheartedly, without envy.",
         etymology="Modern Hebrew slang, likely from Yiddish farginen — to grant, to allow (another person their happiness). Emerged in 1970s Israeli culture.",
         example="When her rival won the prize, she surprised herself — she felt only firgun, genuine and warm.",
         cultural_note="Firgun is considered the antidote to the all-too-human tendency toward jealousy. Israelis consider it a rare and admirable quality.",
         related="Philotimo (Greek)  ·  Ubuntu (Zulu)  ·  Meraki (Greek)",
         quote="No one has ever become poor by giving.",
         quote_author="Anne Frank", out_name="word_feb15.png"),

    dict(day=47, date="February 16", word="Naz", language="Urdu", country="Pakistan", capital="Islamabad",
         pronunciation="[ naaz ]",
         definition="The confidence and pride that comes from being deeply, unconditionally loved — the ease of someone who knows they are cherished.",
         etymology="From Persian and Arabic roots. In Urdu poetry (ghazal), naz describes the dignified assurance of the beloved.",
         example="She entered with naz — not arrogance, but the quiet confidence of someone who has always been loved well.",
         cultural_note="Urdu is a language of refined emotion. Naz appears throughout classical poetry as the defining quality of the beloved.",
         related="Amae (Japanese)  ·  Philotimo (Greek)  ·  Firgun (Hebrew)",
         quote="Even after all this time the sun never says to the earth, 'You owe me.'",
         quote_author="Hafiz", out_name="word_feb16.png"),

    dict(day=48, date="February 17", word="Taarradhin", language="Arabic", country="Jordan", capital="Amman",
         pronunciation="[ tah-RAH-deen ]",
         definition="A mutual, happy compromise in which all parties feel genuinely satisfied — not a grudging middle ground, but a real resolution.",
         etymology="From the Arabic root r-d-y — to be content, to accept. A word for the kind of agreement where everyone actually wins.",
         example="After two hours of negotiation, they reached taarradhin — all three walked out smiling.",
         cultural_note="Arabic has many words for conflict's resolution; taarradhin is the rarest and most beautiful — genuine mutual contentment.",
         related="Philotimo (Greek)  ·  Ubuntu (Zulu)  ·  Lagom (Swedish)",
         quote="Make your enemy your friend, and you will have one less enemy.",
         quote_author="Naguib Mahfouz", out_name="word_feb17.png"),

    dict(day=49, date="February 18", word="Kintsugi", language="Japanese", country="Japan", capital="Tokyo",
         pronunciation="[ kin-TSU-gee ]",
         definition="The art of repairing broken pottery with gold — the philosophy that breakage and repair are part of history, not things to hide.",
         etymology="From kin (gold) + tsugi (to join). A practice dating to 15th-century Japan; now a global philosophy of resilience.",
         example="Her scars, she finally understood, were kintsugi — they made her more herself, not less.",
         cultural_note="Kintsugi embodies wabi-sabi: the broken cup, repaired in gold, is more beautiful and more valuable than before it broke.",
         related="Wabi-sabi (Japanese)  ·  Mono no aware (Japanese)  ·  Sisu (Finnish)",
         quote="The wound is the place where the light enters you.",
         quote_author="Matsuo Bashō", out_name="word_feb18.png"),

    dict(day=50, date="February 19", word="Komorebi", language="Japanese", country="Japan", capital="Tokyo",
         pronunciation="[ ko-mo-REH-bee ]",
         definition="The interplay of light and leaves — sunlight filtering through trees, scattering moving patterns of shadow and gold.",
         etymology="From ko (tree) + more (leaking) + bi (light, sun). A purely visual poetry encoded in a single word.",
         example="She lay in the grass, watching the komorebi shift and dance above her — a living painting.",
         cultural_note="Japanese has dozens of words for light effects and natural phenomena that other languages can only describe in sentences.",
         related="Waldeinsamkeit (German)  ·  Friluftsliv (Norwegian)  ·  Yūgen (Japanese)",
         quote="The clearest way into the Universe is through a forest wilderness.",
         quote_author="Matsuo Bashō", out_name="word_feb19.png"),

    dict(day=51, date="February 20", word="Natsukashii", language="Japanese", country="Japan", capital="Tokyo",
         pronunciation="[ nat-su-KAH-shee ]",
         definition="A fond, warm nostalgia triggered by encountering something from the past — not grief, but the sweet ache of a memory rediscovered.",
         etymology="Old Japanese, rooted in natsu (summer) and the feeling of longing. The summer of childhood as the archetype of all that is missed.",
         example="The smell of her grandmother's kitchen hit her with natsukashii — she was eight years old again, completely.",
         cultural_note="Unlike Western nostalgia, natsukashii has no sadness at its core — it is an embrace of the past, not a mourning of it.",
         related="Saudade (Portuguese)  ·  Hiraeth (Welsh)  ·  Sehnsucht (German)",
         quote="Even the longest night will end, and the sun will rise.",
         quote_author="Victor Hugo", out_name="word_feb20.png"),

    dict(day=52, date="February 21", word="Ukiyo", language="Japanese", country="Japan", capital="Tokyo",
         pronunciation="[ oo-kee-YO ]",
         definition="The floating world — living fully in the present moment, embracing the transient pleasures of art, music, and beauty.",
         etymology="From uki (floating, transient) + yo (world). Originally Buddhist for the suffering world; later reclaimed as joyful impermanence.",
         example="He spent the years after his illness in ukiyo — present, unhurried, awake to every ordinary miracle.",
         cultural_note="The Ukiyo-e woodblock prints of the Edo period captured the floating world in art — Japan's most recognisable aesthetic export.",
         related="Mono no aware (Japanese)  ·  Wabi-sabi (Japanese)  ·  Dolce far niente (Italian)",
         quote="Wherever you are, be all there.",
         quote_author="Kenzaburō Ōe", out_name="word_feb21.png"),

    dict(day=53, date="February 22", word="Kodawari", language="Japanese", country="Japan", capital="Tokyo",
         pronunciation="[ ko-dah-WAH-ree ]",
         definition="An uncompromising devotion to one's craft — the refusal to cut corners, the obsessive commitment to doing things with total integrity.",
         etymology="From kodawaru — to be particular about, to be obsessed with. A positive word in Japanese; perfectionism as a spiritual discipline.",
         example="The ramen chef arrived at 4am every day — his kodawari demanded that the broth be fresh.",
         cultural_note="Kodawari is why Japanese ramen shops have queues around the block — the master's obsession becomes the customer's joy.",
         related="Meraki (Greek)  ·  Sisu (Finnish)  ·  Ikigai (Japanese)",
         quote="In all things of nature there is something of the marvellous.",
         quote_author="Haruki Murakami", out_name="word_feb22.png"),

    dict(day=54, date="February 23", word="Shoganai", language="Japanese", country="Japan", capital="Tokyo",
         pronunciation="[ sho-gah-NAI ]",
         definition="The graceful acceptance of what cannot be changed — 'it cannot be helped'; the wisdom to release what is beyond one's control.",
         etymology="From shō ga nai — there is no way, nothing can be done. A phrase of resignation, but never despair.",
         example="The flight was cancelled. She ordered tea, found a book, and shoganai settled over her like a blanket.",
         cultural_note="Shoganai is central to Japanese resilience — it does not mean giving up, but directing energy away from the uncontrollable.",
         related="Þetta reddast (Icelandic)  ·  Sisu (Finnish)  ·  Acedia (Latin)",
         quote="For every ailment under the sun, there is a remedy or there is none. If there be one, try to find it. If there be none, never mind it.",
         quote_author="Kōbō Abe", out_name="word_feb23.png"),

    dict(day=55, date="February 24", word="Ma", language="Japanese", country="Japan", capital="Tokyo",
         pronunciation="[ mah ]",
         definition="The meaningful pause or empty space between things — the silence in music, the gap in architecture, the breath between words.",
         etymology="Written 間 — literally 'a gate through which the moon is seen'. A concept as much spatial as temporal: the fullness of emptiness.",
         example="The conductor understood ma — it was what he did with the silences that made the music.",
         cultural_note="In Japanese aesthetics, ma is not absence but presence — the negative space that gives form its meaning.",
         related="Wabi-sabi (Japanese)  ·  Yūgen (Japanese)  ·  Dolce far niente (Italian)",
         quote="In the space between thoughts, we find ourselves.",
         quote_author="Yasunari Kawabata", out_name="word_feb24.png"),

    dict(day=56, date="February 25", word="Resfeber", language="Swedish", country="Sweden", capital="Stockholm",
         pronunciation="[ RESS-feh-ber ]",
         definition="The restless, excited anxiety felt before a great journey begins — the racing heart of anticipation and apprehension combined.",
         etymology="From res (journey, travel) + feber (fever). A travel fever: the body's response to the enormity of departure.",
         example="The night before the flight, resfeber kept her awake — half joy, half vertigo.",
         cultural_note="Swedish travel literature is full of resfeber — a nation of explorers who understood that departure is its own emotion.",
         related="Fernweh (German)  ·  Wanderlust (German)  ·  Iktsuarpok (Inuit)",
         quote="Travel is the only thing you buy that makes you richer.",
         quote_author="Astrid Lindgren", out_name="word_feb25.png"),

    dict(day=57, date="February 26", word="Gökotta", language="Swedish", country="Sweden", capital="Stockholm",
         pronunciation="[ YEH-koh-tah ]",
         definition="The act of rising early in the morning specifically to go outside and hear the first birds of spring sing.",
         etymology="From Swedish göka (cuckoo) + kotta (early rising). A tradition so specific it required its own word.",
         example="Every April morning since childhood, she practiced gökotta — the birds were her alarm clock and her prayer.",
         cultural_note="Gökotta is practiced on Ascension Day in Sweden — but the feeling it names belongs to every person who has heard a bird at dawn.",
         related="Friluftsliv (Norwegian)  ·  Komorebi (Japanese)  ·  Waldeinsamkeit (German)",
         quote="The early morning has gold in its mouth.",
         quote_author="August Strindberg", out_name="word_feb26.png"),

    dict(day=58, date="February 27", word="Mysa", language="Swedish", country="Sweden", capital="Stockholm",
         pronunciation="[ MEE-sah ]",
         definition="To be snug and content — the quiet pleasure of being warmly settled in, comfortable in body and mind.",
         etymology="Swedish verb meaning to be cosy or snug. Related to mysig (pleasant, cosy). The active form of hygge — to do cosy.",
         example="They mysa'd all Sunday under a blanket with coffee and a film that neither of them had seen.",
         cultural_note="Swedes distinguish between mysa (active, intentional coziness) and hygge (the atmosphere created) — subtle, important, Swedish.",
         related="Hygge (Danish)  ·  Koselig (Norwegian)  ·  Gezellig (Dutch)",
         quote="Life is short, and it is up to you to make it sweet.",
         quote_author="Selma Lagerlöf", out_name="word_feb27.png"),

    dict(day=59, date="February 28", word="Fika", language="Swedish", country="Sweden", capital="Stockholm",
         pronunciation="[ FEE-kah ]",
         definition="A daily ritual of pausing to drink coffee and eat something sweet in good company — not a coffee break, but a moment of genuine connection.",
         etymology="From kaffi — a reversal of syllables (back-slang) from 19th-century Swedish. Now a cultural institution and a verb.",
         example="Whatever the deadline, the office fika happened at three — that was not negotiable.",
         cultural_note="Swedes consume more coffee per capita than almost any nation. Fika is why — it is not about the coffee, but the pause.",
         related="Sobremesa (Spanish)  ·  Hygge (Danish)  ·  Dolce far niente (Italian)",
         quote="There is no bad coffee, only coffee that could be better.",
         quote_author="Astrid Lindgren", out_name="word_feb28.png"),

    # ═══════════════════════════════════════════════════════════════════════════
    # MARCH — The German Art of Naming Everything
    # ═══════════════════════════════════════════════════════════════════════════

    dict(day=60, date="March 1", word="Schadenfreude", language="German", country="Germany", capital="Berlin",
         pronunciation="[ SHAH-den-froy-deh ]",
         definition="The pleasure one secretly derives from witnessing another person's misfortune or failure.",
         etymology="From Schaden (damage, harm) + Freude (joy). First recorded in English in 1852 — borrowed because no English word existed.",
         example="He tried not to smile when his rival's presentation crashed. He failed. Schadenfreude is shameful and irresistible.",
         cultural_note="German philosophy has always been honest about human nature. Schadenfreude is not condemned — merely named, precisely.",
         related="Pena ajena (Spanish)  ·  Fremdschämen (German)  ·  Litost (Czech)",
         quote="Everything human is pathetic. The secret source of humour is not joy but sorrow.",
         quote_author="Heinrich Heine", out_name="word_mar01.png"),

    dict(day=61, date="March 2", word="Weltschmerz", language="German", country="Germany", capital="Berlin",
         pronunciation="[ VELT-shmerts ]",
         definition="World-weariness — the grief felt when the world as it is falls painfully short of the world as it should be.",
         etymology="From Welt (world) + Schmerz (pain, ache). Coined by Jean Paul Richter in 1827. Used by Byron and Heine.",
         example="Reading the news, she put her phone down and sat very still — consumed by weltschmerz.",
         cultural_note="Weltschmerz is the emotion of the idealist who has not yet given up — grief in the service of hope.",
         related="Toska (Russian)  ·  Sehnsucht (German)  ·  Litost (Czech)",
         quote="The world is a comedy to those that think, a tragedy to those that feel.",
         quote_author="Friedrich Schiller", out_name="word_mar02.png"),

    dict(day=62, date="March 3", word="Torschlusspanik", language="German", country="Germany", capital="Berlin",
         pronunciation="[ TOR-shloos-pah-neek ]",
         definition="The panic that comes from feeling that time is running out — the fear of missed opportunities as life's gates begin to close.",
         etymology="From Tor (gate) + Schluss (closing) + Panik (panic). A medieval image: the city gates closing, leaving you outside.",
         example="At thirty-five, torschlusspanik struck — she signed up for everything at once.",
         cultural_note="Torschlusspanik is the German midlife crisis compressed into a single word. Universal; only Germany named it.",
         related="Sehnsucht (German)  ·  Zielschmerz (German)  ·  Resfeber (Swedish)",
         quote="We are all, at some point, running toward something we may never reach.",
         quote_author="Bertolt Brecht", out_name="word_mar03.png"),

    dict(day=63, date="March 4", word="Fingerspitzengefühl", language="German", country="Germany", capital="Berlin",
         pronunciation="[ FING-er-shpit-zen-geh-fyool ]",
         definition="An intuitive sensitivity and tact — the ability to handle delicate situations with lightness, instinct, and precision.",
         etymology="Literally 'fingertip feeling'. The tactile metaphor for emotional and social intelligence — feeling your way through complexity.",
         example="Negotiating the contract required less legal skill than fingerspitzengefühl — knowing exactly when to speak.",
         cultural_note="German combines physical precision with emotional intelligence: fingerspitzengefühl is the word for wisdom that lives in the hands.",
         related="Philotimo (Greek)  ·  Meraki (Greek)  ·  Kodawari (Japanese)",
         quote="The greatest thing a human soul ever does in this world is to see something.",
         quote_author="Johann Wolfgang von Goethe", out_name="word_mar04.png"),

    dict(day=64, date="March 5", word="Fremdschämen", language="German", country="Germany", capital="Berlin",
         pronunciation="[ FREMD-shay-men ]",
         definition="Vicarious embarrassment — being embarrassed on behalf of someone who does not realise they should be embarrassed.",
         etymology="From fremd (foreign, other) + schämen (to be ashamed). The shame that transfers to you from someone who has lost theirs.",
         example="Watching him interrupt the speaker again, she felt fremdschämen so acute she looked at the floor.",
         cultural_note="Pena ajena in Spanish describes the same phenomenon. That two cultures named it independently suggests just how universal it is.",
         related="Pena ajena (Spanish)  ·  Schadenfreude (German)  ·  Litost (Czech)",
         quote="Man is the only animal that blushes — or needs to.",
         quote_author="Heinrich Heine", out_name="word_mar05.png"),

    dict(day=65, date="March 6", word="Drachenfutter", language="German", country="Germany", capital="Berlin",
         pronunciation="[ DRAKH-en-foot-er ]",
         definition="A peace offering given to a partner after a transgression — a gift that acknowledges guilt before the argument begins.",
         etymology="Literally 'dragon fodder'. The dragon is the offended partner; the fodder is chocolate, flowers, or whatever appeases them.",
         example="He arrived home two hours late with drachenfutter — a good bottle and her favourite flowers.",
         cultural_note="German has an entire vocabulary of relationship management. Drachenfutter is its most practical and self-aware entry.",
         related="Taarradhin (Arabic)  ·  Forelsket (Norwegian)  ·  Cafuné (Portuguese)",
         quote="The secret of a good marriage is to know when to be silent.",
         quote_author="Thomas Mann", out_name="word_mar06.png"),

    dict(day=66, date="March 7", word="Verschlimmbessern", language="German", country="Germany", capital="Berlin",
         pronunciation="[ fer-SHLIM-bes-ern ]",
         definition="To make something worse in the process of trying to improve it — the well-meaning intervention that creates new problems.",
         etymology="From verschlimmern (to worsen) + verbessern (to improve). A portmanteau of the two directions of change — tragically merged.",
         example="She tried to fix the wobbly table leg and verschlimmbessert the whole thing into firewood.",
         cultural_note="German humour is often encoded in its compound words. Verschlimmbessern is both a warning and a gentle laugh at human ambition.",
         related="Schadenfreude (German)  ·  Torschlusspanik (German)  ·  Litost (Czech)",
         quote="We have met the enemy and he is us.",
         quote_author="Bertolt Brecht", out_name="word_mar07.png"),

    dict(day=67, date="March 8", word="Kummerspeck", language="German", country="Germany", capital="Berlin",
         pronunciation="[ KOO-mer-shpek ]",
         definition="The weight gained through emotional eating — the extra pounds acquired from the comfort food consumed during grief, stress, or heartbreak.",
         etymology="Literally 'grief bacon'. Kummer (grief, sorrow) + Speck (bacon, fat). German honesty at its most nutritional.",
         example="After the breakup, three weeks of kummerspeck had accumulated — she renamed it 'healing weight'.",
         cultural_note="Germans excel at giving friendly, slightly absurd names to painful experiences. Kummerspeck is embarrassing and completely relatable.",
         related="Litost (Czech)  ·  Toska (Russian)  ·  Weltschmerz (German)",
         quote="The only way out of the labyrinth of suffering is to forgive.",
         quote_author="Franz Kafka", out_name="word_mar08.png"),

    dict(day=68, date="March 9", word="Weltanschauung", language="German", country="Germany", capital="Berlin",
         pronunciation="[ VELT-an-show-oong ]",
         definition="One's comprehensive framework for understanding the world — a complete worldview through which all experience is filtered and interpreted.",
         etymology="From Welt (world) + Anschauung (perception, contemplation). Coined in Kantian philosophy; now used across languages.",
         example="Their argument was not about facts — they had different weltanschauungen, and facts were beside the point.",
         cultural_note="German philosophy gave the world its vocabulary of thought: weltanschauung, zeitgeist, angst — ideas that required German to exist.",
         related="Eudaimonia (Greek)  ·  Ikigai (Japanese)  ·  Raison d'être (French)",
         quote="The world is will and representation.",
         quote_author="Arthur Schopenhauer", out_name="word_mar09.png"),

    dict(day=69, date="March 10", word="Zielschmerz", language="German", country="Germany", capital="Berlin",
         pronunciation="[ TSEEL-shmerts ]",
         definition="The dread that arrives when you are about to get what you have always wanted — the fear of achieving the very goal you sought.",
         etymology="From Ziel (goal, aim) + Schmerz (pain). The anxiety that what lies at the destination may disappoint the journey.",
         example="She had worked fifteen years for this promotion. Now, on the eve of it, zielschmerz paralysed her.",
         cultural_note="Zielschmerz captures the paradox of ambition — we need the goal to move, but dread arriving. Every dreamer knows this.",
         related="Torschlusspanik (German)  ·  Sehnsucht (German)  ·  Resfeber (Swedish)",
         quote="The greatest danger for most of us is not that our aim is too high and we miss it, but that it is too low and we reach it.",
         quote_author="Friedrich Nietzsche", out_name="word_mar10.png"),

    dict(day=70, date="March 11", word="Sturmfrei", language="German", country="Germany", capital="Berlin",
         pronunciation="[ SHTOORM-fry ]",
         definition="The particular freedom and wild energy of having the house entirely to yourself — the liberation of being alone in your own space.",
         etymology="Literally 'storm-free'. Originally a military term for a fortress that cannot be stormed; evolved into domestic freedom.",
         example="Her flatmates left for the weekend — she had sturmfrei and did absolutely everything she normally couldn't.",
         cultural_note="German domestic life is serious and communal. Sturmfrei is its joyous escape valve — the pleasure of the self temporarily unobserved.",
         related="Waldeinsamkeit (German)  ·  Dolce far niente (Italian)  ·  Ma (Japanese)",
         quote="One must have chaos in oneself to give birth to a dancing star.",
         quote_author="Friedrich Nietzsche", out_name="word_mar11.png"),

    dict(day=71, date="March 12", word="Ruinenlust", language="German", country="Germany", capital="Berlin",
         pronunciation="[ ROO-ee-nen-loost ]",
         definition="The pleasure and contemplative melancholy derived from ruins — the strange joy of standing where civilisations have fallen.",
         etymology="From Ruinen (ruins) + Lust (pleasure, desire). A Romantic concept; German painters made it a genre in the 18th century.",
         example="She loved abandoned buildings — that ruinenlust drew her to places where time had been honest.",
         cultural_note="The Romantic movement glorified ruins as proof of nature's triumph over human ambition. Ruinenlust is its lasting emotional legacy.",
         related="Weltschmerz (German)  ·  Saudade (Portuguese)  ·  Hiraeth (Welsh)",
         quote="To build is to collaborate with the earth, to put a human mark upon the landscape.",
         quote_author="Johann Wolfgang von Goethe", out_name="word_mar12.png"),

    dict(day=72, date="March 13", word="Schnapsidee", language="German", country="Germany", capital="Berlin",
         pronunciation="[ SHNAPS-ee-day ]",
         definition="A crazy idea that seems brilliant when drunk — the inspired, ridiculous plan conceived under the influence and regretted by morning.",
         etymology="From Schnaps (spirits, schnapps) + Idee (idea). The booze-born brainwave that deserves its own word.",
         example="Building a treehouse for adults had seemed like a schnapsidee. Three years later, it was booked solid.",
         cultural_note="Germany's capacity to name absurdity with precision is its great gift to linguistics. Some schnapsideen actually work.",
         related="Verschlimmbessern (German)  ·  Drachenfutter (German)  ·  Chutzpah (Yiddish)",
         quote="Madness is rare in individuals, but in groups, it is the rule.",
         quote_author="Friedrich Nietzsche", out_name="word_mar13.png"),

    dict(day=73, date="March 14", word="Doppelgänger", language="German", country="Germany", capital="Berlin",
         pronunciation="[ DOP-el-geng-er ]",
         definition="A ghostly double of a living person — one's exact physical counterpart, seen as an omen or uncanny mirror of the self.",
         etymology="From Doppel (double) + Gänger (walker, goer). Literally 'double walker'. Popularised by German Romantic literature.",
         example="She rounded a corner in Berlin and stopped dead — a stranger who wore her face walked past.",
         cultural_note="In German folklore, seeing one's doppelgänger is an omen of death. In modern use, it's the uncanny joy of discovering a stranger twin.",
         related="Zeitgeist (German)  ·  Weltanschauung (German)  ·  Angst (German)",
         quote="The unconscious is the largest part of ourselves.",
         quote_author="Carl Jung", out_name="word_mar14.png"),

    dict(day=74, date="March 15", word="Zeitgeist", language="German", country="Germany", capital="Berlin",
         pronunciation="[ TSYT-gyst ]",
         definition="The spirit of the times — the defining mood, beliefs, and attitudes that characterise a particular historical moment.",
         etymology="From Zeit (time) + Geist (spirit, ghost). Popularised by Hegel to describe the intellectual climate of an era.",
         example="The exhibition captured the zeitgeist perfectly — anxious, ironic, and obsessed with identity.",
         cultural_note="German idealism gave the world zeitgeist as a tool for understanding history. Even Google named a data trend report after it.",
         related="Weltanschauung (German)  ·  Weltschmerz (German)  ·  Doppelgänger (German)",
         quote="History repeats itself, first as tragedy, then as farce.",
         quote_author="Karl Marx", out_name="word_mar15.png"),

    dict(day=75, date="March 16", word="Schwellenangst", language="German", country="Germany", capital="Berlin",
         pronunciation="[ SHVEL-en-angst ]",
         definition="The anxiety felt at the threshold of a new experience — the fear of crossing over into the unfamiliar, from the known to the unknown.",
         etymology="From Schwelle (threshold, step) + Angst (anxiety). The emotional experience of the doorway — literally, of crossing over.",
         example="She paused outside the gallery every Tuesday, schwellenangst rooting her to the pavement before she went in.",
         cultural_note="In psychology, schwellenangst is linked to change anxiety. Therapists who work with it give it this precise German name.",
         related="Torschlusspanik (German)  ·  Resfeber (Swedish)  ·  Angst (German)",
         quote="Courage is not the absence of fear, but the judgment that something else is more important than fear.",
         quote_author="Ambrose Bierce", out_name="word_mar16.png"),

    dict(day=76, date="March 17", word="Stammtisch", language="German", country="Germany", capital="Berlin",
         pronunciation="[ SHTAM-tish ]",
         definition="A regular gathering of friends or colleagues at the same table in the same pub — a standing social institution.",
         etymology="From Stamm (trunk, regular) + Tisch (table). The regulars' table: reserved, familiar, and never explained to outsiders.",
         example="The stammtisch met every Thursday at seven. It had done so for twenty-two years. Nobody knew who had started it.",
         cultural_note="Stammtisch is not just a table — it is a community, a ritual, and a model of how friendship is sustained over time.",
         related="Sobremesa (Spanish)  ·  Hygge (Danish)  ·  Gezellig (Dutch)",
         quote="Friendship is the only cement that will ever hold the world together.",
         quote_author="Bertolt Brecht", out_name="word_mar17.png"),

    dict(day=77, date="March 18", word="Backpfeifengesicht", language="German", country="Germany", capital="Berlin",
         pronunciation="[ BAK-pfy-fen-geh-zikt ]",
         definition="A face that is urgently in need of a slap — a person whose expression provokes an involuntary and very specific frustration.",
         etymology="From Backpfeife (slap) + Gesicht (face). German's most satisfying compound: the precise naming of a universal irritation.",
         example="The committee chair had a classic backpfeifengesicht. This was never said aloud. It was always thought.",
         cultural_note="German has always believed that if a thing exists, it deserves a name. Backpfeifengesicht is proof this extends to faces.",
         related="Fremdschämen (German)  ·  Schadenfreude (German)  ·  Pena ajena (Spanish)",
         quote="Against stupidity the gods themselves struggle in vain.",
         quote_author="Friedrich Schiller", out_name="word_mar18.png"),

    dict(day=78, date="March 19", word="Angst", language="German", country="Germany", capital="Berlin",
         pronunciation="[ angst ]",
         definition="A deep, existential anxiety — not about any specific danger, but about the fundamental uncertainty and weight of existence itself.",
         etymology="From Old High German angust (narrowness, constriction). Kierkegaard theorised it as the dizziness of freedom; Freud absorbed it into psychology.",
         example="The anxiety of adolescence has its own name: angst — the discovery that the world is both vast and indifferent.",
         cultural_note="Kierkegaard's angst is the dizziness felt when looking into the abyss of freedom. It is the price of consciousness.",
         related="Weltschmerz (German)  ·  Toska (Russian)  ·  Sehnsucht (German)",
         quote="Anxiety is the dizziness of freedom.",
         quote_author="Søren Kierkegaard", out_name="word_mar19.png"),

    dict(day=79, date="March 20", word="Zweisamkeit", language="German", country="Germany", capital="Berlin",
         pronunciation="[ TSVY-zam-kite ]",
         definition="The togetherness of two — the intimate, private world that exists only between two people who are completely at ease with each other.",
         etymology="From zwei (two) + Einsamkeit (solitude) — literally 'two-solitude'. Solitude, but shared. Alone, but together.",
         example="They had reached zweisamkeit — they could sit in the same room for hours without speaking and it felt like enough.",
         cultural_note="German Romanticism celebrated the intimacy of two souls fused — zweisamkeit is the philosophical version of a long marriage.",
         related="Amae (Japanese)  ·  Cafuné (Portuguese)  ·  Hygge (Danish)",
         quote="Where you are, I want to be.",
         quote_author="Johann Wolfgang von Goethe", out_name="word_mar20.png"),

    dict(day=80, date="March 21", word="Kvell", language="Yiddish", country="Israel", capital="Jerusalem",
         pronunciation="[ kvel ]",
         definition="To beam with pride and joy over the achievement of a loved one — particularly a child — to glow with uncontainable parental delight.",
         etymology="From German quellen — to well up, to overflow. In Yiddish, it became the word for a specific, irresistible parental pride.",
         example="He kvelled at the graduation — he had cried at rehearsal and he cried again at the real thing.",
         cultural_note="Yiddish is a language of emotional precision — kvell, naches, and tsuris together map the full arc of parental love.",
         related="Naches (Yiddish)  ·  Firgun (Hebrew)  ·  Philotimo (Greek)",
         quote="A mother understands what a child does not say.",
         quote_author="Sholem Aleichem", out_name="word_mar21.png"),

    dict(day=81, date="March 22", word="Chutzpah", language="Yiddish", country="Israel", capital="Jerusalem",
         pronunciation="[ KHOOTS-pah ]",
         definition="Audacious nerve and brazen self-confidence — the quality of doing something outrageously bold with no apology and no shame.",
         etymology="From Hebrew chutzpah — impudence, effrontery. In Yiddish it evolved from purely negative to include admiration for sheer nerve.",
         example="She walked into the publisher's office without an appointment and walked out with a book deal. Pure chutzpah.",
         cultural_note="Leo Rosten defined chutzpah with the classic example: a man who kills his parents, then begs for mercy as an orphan.",
         related="Sisu (Finnish)  ·  Philotimo (Greek)  ·  Meraki (Greek)",
         quote="Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
         quote_author="Elie Wiesel", out_name="word_mar22.png"),

    dict(day=82, date="March 23", word="Mensch", language="Yiddish", country="Israel", capital="Jerusalem",
         pronunciation="[ mench ]",
         definition="A person of integrity, decency, and genuine humanity — someone who does the right thing not for reward but because it is right.",
         etymology="From German Mensch (human being, person). In Yiddish, it elevated the ordinary word into the highest ethical compliment.",
         example="He drove two hundred kilometres to attend the funeral of someone he barely knew. He was a mensch.",
         cultural_note="To call someone a mensch in Yiddish is among the highest compliments possible — more than clever, more than successful: truly good.",
         related="Ubuntu (Zulu)  ·  Philotimo (Greek)  ·  Firgun (Hebrew)",
         quote="Above all, be a good person.",
         quote_author="Isaac Bashevis Singer", out_name="word_mar23.png"),

    dict(day=83, date="March 24", word="Naches", language="Yiddish", country="Israel", capital="Jerusalem",
         pronunciation="[ NAH-khes ]",
         definition="Pride and joy derived from the accomplishments of one's children — the specific, deep satisfaction of a parent who sees their child flourish.",
         etymology="From Hebrew nachat — contentment, peace of mind. In Yiddish, it evolved to mean the particular pleasure of parental pride.",
         example="When her daughter received the award, the naches she felt was physical — it moved through her like warmth.",
         cultural_note="Kvell is the expression of naches; naches is the feeling beneath it. Together they define the emotional heart of Yiddish family life.",
         related="Kvell (Yiddish)  ·  Firgun (Hebrew)  ·  Philotimo (Greek)",
         quote="The best thing parents can give their children is roots and wings.",
         quote_author="Sholem Aleichem", out_name="word_mar24.png"),

    dict(day=84, date="March 25", word="Bashert", language="Yiddish", country="Israel", capital="Jerusalem",
         pronunciation="[ bah-SHERT ]",
         definition="Destined — something or someone that was meant to be, fated by forces beyond human understanding or control.",
         etymology="From Hebrew b'shert — as fated. In Yiddish, most commonly used of a destined soulmate: your person, chosen by the universe.",
         example="They had met by accident three times in three cities. By the third, they both said bashert.",
         cultural_note="In Jewish tradition, bashert reflects a belief that certain meetings are written in a book long before they happen.",
         related="Koi no yokan (Japanese)  ·  Forelsket (Norwegian)  ·  Mamihlapinatapai (Yaghan)",
         quote="Love is not something you find. Love is something that finds you.",
         quote_author="Lorrie Moore", out_name="word_mar25.png"),

    dict(day=85, date="March 26", word="Verklempt", language="Yiddish", country="Israel", capital="Jerusalem",
         pronunciation="[ fer-KLEMPT ]",
         definition="Overcome with emotion — particularly a combination of joy and grief — to the point of being unable to speak.",
         etymology="From German verklemmt — stuck, jammed. In Yiddish, emotionally jammed: the throat closed by feeling too large to fit in words.",
         example="At the wedding toast, he stood there verklempt, holding the microphone, saying nothing useful.",
         cultural_note="Yiddish is uniquely suited to emotions that resist clean naming — verklempt is the word for when emotion exceeds language.",
         related="Naches (Yiddish)  ·  Kvell (Yiddish)  ·  Mono no aware (Japanese)",
         quote="Laughter through tears is my favourite emotion.",
         quote_author="Sholem Aleichem", out_name="word_mar26.png"),

    dict(day=86, date="March 27", word="Tsuris", language="Yiddish", country="Israel", capital="Jerusalem",
         pronunciation="[ TSOO-ris ]",
         definition="Troubles, worries, and aggravations — a cumulative weight of small difficulties that together constitute the texture of a difficult life.",
         etymology="From Hebrew tzarot — troubles, distress. In Yiddish, it became warm, comic, and resigned — trouble with a sigh.",
         example="The car, the tooth, the neighbour's dog — he had enough tsuris without looking for more.",
         cultural_note="Yiddish transforms suffering into literature. Tsuris is not self-pity but self-awareness — trouble acknowledged with dark humour.",
         related="Toska (Russian)  ·  Litost (Czech)  ·  Weltschmerz (German)",
         quote="Without suffering there would be no literature.",
         quote_author="Isaac Bashevis Singer", out_name="word_mar27.png"),

    dict(day=87, date="March 28", word="Tikkun olam", language="Hebrew", country="Israel", capital="Jerusalem",
         pronunciation="[ tee-KOON oh-LAHM ]",
         definition="Repairing the world — the moral obligation to act in ways that heal injustice, reduce suffering, and improve the human condition.",
         etymology="From Hebrew tikkun (repair, correction) + olam (world). A Kabbalistic concept; central to modern Jewish ethics and social action.",
         example="She became a doctor for tikkun olam — not the prestige, but the sense of mending something broken.",
         cultural_note="Tikkun olam has become the animating ethic of Jewish social justice movements worldwide — the imperative to act, not only to believe.",
         related="Ubuntu (Zulu)  ·  Philotimo (Greek)  ·  Meraki (Greek)",
         quote="Whoever saves a single soul, Scripture accounts it as if he had saved an entire world.",
         quote_author="The Talmud", out_name="word_mar28.png"),

    dict(day=88, date="March 29", word="Gluggavedur", language="Icelandic", country="Iceland", capital="Reykjavík",
         pronunciation="[ GLUG-ah-veh-dur ]",
         definition="Weather that is beautiful to look at from indoors but too harsh, cold, or wild to actually go outside and experience.",
         etymology="From gluggi (window) + veður (weather). Window-weather: the panorama of storms best appreciated through glass with a warm drink.",
         example="The blizzard was gluggavedur — she watched it from the sofa with tea and did not feel one bit of guilt.",
         cultural_note="Iceland's brutal winters gave it the richest vocabulary of weather in the world. Gluggavedur is its most comforting entry.",
         related="Hygge (Danish)  ·  Koselig (Norwegian)  ·  Mysa (Swedish)",
         quote="The world is full of beauty, and storms are part of its beauty.",
         quote_author="Halldór Laxness", out_name="word_mar29.png"),

    dict(day=89, date="March 30", word="Þetta reddast", language="Icelandic", country="Iceland", capital="Reykjavík",
         pronunciation="[ THET-ah RED-ast ]",
         definition="'It will all work out' — the Icelandic philosophy of optimistic resilience in the face of chaos and uncertainty.",
         etymology="Literally 'this will fix itself'. A national mantra born of centuries of volcanic eruptions, harsh winters, and economic crises.",
         example="The ferry was cancelled, the guesthouse was full, the road was closed. Þetta reddast, she said, and meant it.",
         cultural_note="Icelanders adopted this phrase as a national philosophy — they have survived everything, and so they believe in everything working out.",
         related="Shoganai (Japanese)  ·  Sisu (Finnish)  ·  Lagom (Swedish)",
         quote="The greatest glory in living lies not in never falling, but in rising every time we fall.",
         quote_author="Halldór Laxness", out_name="word_mar30.png"),

    dict(day=90, date="March 31", word="Hoppipolla", language="Icelandic", country="Iceland", capital="Reykjavík",
         pronunciation="[ HOP-ee-pol-ah ]",
         definition="Jumping into puddles — an act of joyful, childlike abandon; the deliberate choice to splash into life rather than step around it.",
         etymology="From hoppa (to jump) + í (into) + polla (puddle). Made internationally famous by the Icelandic band Sigur Rós.",
         example="She was forty-three when she jumped in the puddle. The children cheered. She did it again.",
         cultural_note="Sigur Rós named one of their most celebrated pieces after this word — Iceland distilled into a single, joyful, soaking splash.",
         related="Friluftsliv (Norwegian)  ·  Gökotta (Swedish)  ·  Joie de vivre (French)",
         quote="You can't stay in your corner of the forest waiting for others to come to you. You have to go to them sometimes.",
         quote_author="Sjón", out_name="word_mar31.png"),

]
